from __future__ import annotations

import os

SERVICE_NAME = "auth-service"
SERVICE_VERSION = "0.1.0"

JWT_SECRET_ENV = "JWT_SECRET"
JWT_SECRET = os.getenv(JWT_SECRET_ENV)
JWT_SECRET_MISSING_ERROR = f"{JWT_SECRET_ENV} environment variable is not set"

JWT_ALGORITHM_ENV = "JWT_ALGORITHM"
JWT_ALGORITHM_DEFAULT = "HS256"
JWT_ALGORITHM = os.getenv(JWT_ALGORITHM_ENV) or JWT_ALGORITHM_DEFAULT

ACCESS_TOKEN_TTL_MIN_ENV = "ACCESS_TOKEN_TTL_MIN"
ACCESS_TOKEN_TTL_MIN_DEFAULT = "15"
ACCESS_TOKEN_TTL_MIN = int(os.getenv(ACCESS_TOKEN_TTL_MIN_ENV, ACCESS_TOKEN_TTL_MIN_DEFAULT))

REFRESH_TOKEN_TTL_DAYS_ENV = "REFRESH_TOKEN_TTL_DAYS"
REFRESH_TOKEN_TTL_DAYS_DEFAULT = "30"
REFRESH_TOKEN_TTL_DAYS = int(os.getenv(REFRESH_TOKEN_TTL_DAYS_ENV, REFRESH_TOKEN_TTL_DAYS_DEFAULT))

BCRYPT_ROUNDS_ENV = "BCRYPT_ROUNDS"
BCRYPT_ROUNDS_DEFAULT = "12"
BCRYPT_ROUNDS = int(os.getenv(BCRYPT_ROUNDS_ENV, BCRYPT_ROUNDS_DEFAULT))

SERVICE_LOG_PREFIX = f"[{SERVICE_NAME}]"
