from __future__ import annotations

import os

SERVICE_NAME = "auth-service"
SERVICE_VERSION = "0.1.0"

JWT_SECRET_ENV = "JWT_SECRET"
JWT_SECRET = os.getenv(JWT_SECRET_ENV)
JWT_SECRET_MISSING_ERROR = f"{JWT_SECRET_ENV} environment variable is not set"

JWT_ALGORITHM_ENV = "JWT_ALGORITHM"
JWT_ALGORITHM_DEFAULT = "HS256"
JWT_ALGORITHM = os.getenv(JWT_ALGORITHM_ENV) or JWT_ALGORITHM_DEFAULT

ACCESS_TOKEN_TTL_MIN_ENV = "ACCESS_TOKEN_TTL_MIN"
ACCESS_TOKEN_TTL_MIN_DEFAULT = "15"
ACCESS_TOKEN_TTL_MIN = int(os.getenv(ACCESS_TOKEN_TTL_MIN_ENV, ACCESS_TOKEN_TTL_MIN_DEFAULT))

REFRESH_TOKEN_TTL_DAYS_ENV = "REFRESH_TOKEN_TTL_DAYS"
REFRESH_TOKEN_TTL_DAYS_DEFAULT = "30"
REFRESH_TOKEN_TTL_DAYS = int(os.getenv(REFRESH_TOKEN_TTL_DAYS_ENV, REFRESH_TOKEN_TTL_DAYS_DEFAULT))

BCRYPT_ROUNDS_ENV = "BCRYPT_ROUNDS"
BCRYPT_ROUNDS_DEFAULT = "12"
BCRYPT_ROUNDS = int(os.getenv(BCRYPT_ROUNDS_ENV, BCRYPT_ROUNDS_DEFAULT))

PASSWORD_RESET_TOKEN_TTL_MIN_ENV = "PASSWORD_RESET_TOKEN_TTL_MIN"
PASSWORD_RESET_TOKEN_TTL_MIN_DEFAULT = "60"
PASSWORD_RESET_TOKEN_TTL_MIN = int(
    os.getenv(PASSWORD_RESET_TOKEN_TTL_MIN_ENV, PASSWORD_RESET_TOKEN_TTL_MIN_DEFAULT)
)

PASSWORD_RESET_BASE_URL_ENV = "PASSWORD_RESET_BASE_URL"
PASSWORD_RESET_BASE_URL_DEFAULT = "http://localhost:3000/reset-password"
PASSWORD_RESET_BASE_URL = os.getenv(
    PASSWORD_RESET_BASE_URL_ENV,
    PASSWORD_RESET_BASE_URL_DEFAULT,
)

PASSWORD_RESET_INCLUDE_DEBUG_TOKEN_ENV = "PASSWORD_RESET_INCLUDE_DEBUG_TOKEN"
PASSWORD_RESET_INCLUDE_DEBUG_TOKEN = (
    os.getenv(PASSWORD_RESET_INCLUDE_DEBUG_TOKEN_ENV, "").lower()
    in {"1", "true", "yes", "on"}
)

PASSWORD_RESET_EMAIL_BACKEND_ENV = "PASSWORD_RESET_EMAIL_BACKEND"
PASSWORD_RESET_EMAIL_BACKEND_DEFAULT = "console"
PASSWORD_RESET_EMAIL_BACKEND = os.getenv(
    PASSWORD_RESET_EMAIL_BACKEND_ENV,
    PASSWORD_RESET_EMAIL_BACKEND_DEFAULT,
).lower()

SMTP_HOST_ENV = "SMTP_HOST"
SMTP_HOST = os.getenv(SMTP_HOST_ENV)

SMTP_PORT_ENV = "SMTP_PORT"
SMTP_PORT_DEFAULT = "587"
SMTP_PORT = int(os.getenv(SMTP_PORT_ENV, SMTP_PORT_DEFAULT))

SMTP_USERNAME_ENV = "SMTP_USERNAME"
SMTP_USERNAME = os.getenv(SMTP_USERNAME_ENV)

SMTP_PASSWORD_ENV = "SMTP_PASSWORD"
SMTP_PASSWORD = os.getenv(SMTP_PASSWORD_ENV)

SMTP_FROM_EMAIL_ENV = "SMTP_FROM_EMAIL"
SMTP_FROM_EMAIL_DEFAULT = "no-reply@localhost"
SMTP_FROM_EMAIL = os.getenv(SMTP_FROM_EMAIL_ENV, SMTP_FROM_EMAIL_DEFAULT)

SMTP_USE_TLS_ENV = "SMTP_USE_TLS"
SMTP_USE_TLS = os.getenv(SMTP_USE_TLS_ENV, "true").lower() in {"1", "true", "yes", "on"}

SMTP_TIMEOUT_SECONDS_ENV = "SMTP_TIMEOUT_SECONDS"
SMTP_TIMEOUT_SECONDS_DEFAULT = "10"
SMTP_TIMEOUT_SECONDS = float(
    os.getenv(SMTP_TIMEOUT_SECONDS_ENV, SMTP_TIMEOUT_SECONDS_DEFAULT)
)

SERVICE_LOG_PREFIX = f"[{SERVICE_NAME}]"